#!/bin/bash

choices="laptop-only\nlaptop-plus-vga\nlaptop-plus-hdmi\nvga-copy\nhdmi-copy\nvga-only\nhdmi-only\ncancel"
title="display"

chosen=$(echo -e "$choices" | rofi -lines 8 -dmenu -p "$title")

case "$chosen" in
    laptop-only)        xrandr --output LVDS1 --auto --output VGA1 --off                      --output HDMI1 --off                       ;;
    vga-only)           xrandr --output LVDS1 --off  --output VGA1 --auto                     --output HDMI1 --off                       ;;
    hdmi-only)          xrandr --output LVDS1 --off  --output VGA1 --auto                     --output HDMI1 --auto                      ;;
    laptop-plus-vga)    xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1   --output HDMI1 --off                       ;;
    laptop-plus-hdmi)   xrandr --output LVDS1 --auto --output VGA1 --off                      --output HDMI1 --auto --right-of LVDS1    ;;
    vga-copy)           xrandr --output LVDS1 --auto --output VGA1 --auto --same-as LVDS1    --output HDMI1 --off                       ;;
    hdmi-copy)          xrandr --output LVDS1 --auto --output VGA1 --off                      --output HDMI1 --auto --same-as LVDS1     ;;
esac


